### ISSUE TITLE
Input time Block Calendar 

### ISSUE THREAD

**Issue by catrafa** [catrafa/capstone-project#3]
**Value Proposition**
Time Block Calendar 
As a participant of a calendar of another person I need to would like to share time windows where both can find time without having other participants of work colleagues  to be able to share the calendar like this.
**Description**

![Unbenannt-2022-07-27-2108](https://user-images.githubusercontent.com/109967772/191269947-afa1478c-7c43-4487-9bd3-f1f2c8dfe00e.png)

Acceptance Criteria
 describe every scenario in detail
 e.g. All Inputs are required, show warning if empty.
 - [] be able to view the shared calendar of the other after it the Time Block it has been shared
 - [ ] So that the occupied time slots are already blocked where appointments are already scheduled
 - [ ] When you click the Submit button, a new calendar entry will appear and a notification will be displayed for the shared calendar.

**Tasks**
(for developers team)
 - [] create a new project with npx create-next-app@latest
 - [ ] create a branch
 - [ ] create a h1 for a App name for the Time Block Calendar 
 - [ ] create a Time Block
